extends:
  - prettier
  - eslint:recommended
plugins:
  - prettier
  - '@typescript-eslint'
env:
  node: true
  es6: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: 'module'
  ecmaVersion: 2018
rules:
  prettier/prettier: error
  prefer-const: error
  no-unused-vars: 0
